/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDemoConvexRouteImport } from './routes/_app.demo.convex'
import { Route as AppDemoAuthRouteImport } fro./routes/_app.demo.auth.tsxemo.auth'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDemoConvexRoute = AppDemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoAuthRoute = AppDemoAuthRouteImport.update({
  id: '/demo/auth',
  path: '/demo/auth',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/auth': typeof AppDemoAuthRoute
  '/demo/convex': typeof AppDemoConvexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/auth': typeof AppDemoAuthRoute
  '/demo/convex': typeof AppDemoConvexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/demo/auth': typeof AppDemoAuthRoute
  '/_app/demo/convex': typeof AppDemoConvexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/auth' | '/demo/convex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/auth' | '/demo/convex'
  id: '__root__' | '/' | '/_app' | '/_app/demo/auth' | '/_app/demo/convex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/demo/convex': {
      id: '/_app/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof AppDemoConvexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/auth': {
      id: '/_app/demo/auth'
      path: '/demo/auth'
      fullPath: '/demo/auth'
      preLoaderRoute: typeof AppDemoAuthRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDemoAuthRoute: typeof AppDemoAuthRoute
  AppDemoConvexRoute: typeof AppDemoConvexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDemoAuthRoute: AppDemoAuthRoute,
  AppDemoConvexRoute: AppDemoConvexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
